### ISSUE TITLE
Techdocs does not work anymore after adding api-linter-plugin

### ISSUE THREAD

**Issue by daydy16** [zalando/backstage-plugin-api-linter#24]
## Expected Behaviour
API-Linter Plugin and TechDocs work together

## Actual Behaviour
After exporting the plugin `export { APILinterPlugin } from 'backstage-plugin-api-linter';`  techdocs ui doesnt work anymore.
It keeps loading as long as i remove the export of the plugin.
![image](https://user-images.githubusercontent.com/23737896/187677342-a5812704-a0ca-400a-a344-2b8881630304.png)
I unfortunately dont see any errors in the log and can't explain why this happens.

## Steps to Reproduce the Problem
1. install backstage with techdocs 
2. add zally linter plugin as described [here](https://github.com/zalando/backstage-plugin-api-linter)
3. techdocs doesnt work anymore

## Specifications 

* Version: Backstage 1.4
* Platform: Windows 10 with Ubuntu WSL, but it also appears with Docker local and in k8s

**Comment by daydy16** [comment]
I could fix it after updating the  "@backstage/core-plugin-api" dependency from ^0.7.0 to "^1.0.5"

**Comment by Beihao-Zhou** [comment]
I met this problem now as well again. Could you please share what version of api-docs-plugin you used? @daydy16 Thank you so much!

**Comment by Beihao-Zhou** [comment]
The error I have is like this: 
```
2022-11-04T20:38:49.162Z backstage error Missing index for techdocs. This could be because the index hasn't been created yet or there was a problem during index creation. type=errorHandler name=MissingIndexError cause=undefined stack=MissingIndexError: Missing index for techdocs. This could be because the index hasn't been created yet or there was a problem during index creation.
    at LunrSearchEngine.query (/Users/beihaozhou/Projects/pivot/fabric/node_modules/@backstage/plugin-search-backend-node/dist/index.cjs.js:426:13)
    at /Users/beihaozhou/Projects/pivot/fabric/node_modules/@backstage/plugin-search-backend/dist/index.cjs.js:246:67
    at handleReturn (/Users/beihaozhou/Projects/pivot/fabric/node_modules/express-promise-router/lib/express-promise-router.js:24:23)
    at /Users/beihaozhou/Projects/pivot/fabric/node_modules/express-promise-router/lib/express-promise-router.js:64:7
    at handleReturn (/Users/beihaozhou/Projects/pivot/fabric/node_modules/express-promise-router/lib/express-promise-router.js:24:23)
    at /Users/beihaozhou/Projects/pivot/fabric/node_modules/express-promise-router/lib/express-promise-router.js:64:7
    at Layer.handle [as handle_request] (/Users/beihaozhou/Projects/pivot/fabric/node_modules/express/lib/router/layer.js:95:5)
    at next (/Users/beihaozhou/Projects/pivot/fabric/node_modules/express/lib/router/route.js:144:13)
    at Route.dispatch (/Users/beihaozhou/Projects/pivot/fabric/node_modules/express/lib/router/route.js:114:3)
    at Layer.handle [as handle_request] (/Users/beihaozhou/Projects/pivot/fabric/node_modules/express/lib/router/layer.js:95:5)
    at /Users/beihaozhou/Projects/pivot/fabric/node_modules/express/lib/router/index.js:284:15
    at Function.process_params (/Users/beihaozhou/Projects/pivot/fabric/node_modules/express/lib/router/index.js:346:12)
    at next (/Users/beihaozhou/Projects/pivot/fabric/node_modules/express/lib/router/index.js:280:10)
    at Function.handle (/Users/beihaozhou/Projects/pivot/fabric/node_modules/express/lib/router/index.js:175:3)
    at router (/Users/beihaozhou/Projects/pivot/fabric/node_modules/express/lib/router/index.js:47:12)
    at handleReturn (/Users/beihaozhou/Projects/pivot/fabric/node_modules/express-promise-router/lib/express-promise-router.js:24:23)
```

**Comment by daydy16** [comment]
I had the same error. If I remember correctly the issue was caused by the outdated api-core-plugin version. I fixed it by using and overwrite in the package.json
`
  "overrides": {
    "backstage-plugin-api-linter": {
      "@backstage/core-plugin-api": "^1.0.4"
    }
  },
`

In my `App.tsx` I had to ignore an error (with ` //@ts-ignore`) due to some missing properties in the zally plugin implementation
`
const app = createApp({
  apis,
  //@ts-ignore
  plugins: Object.values(plugins),
  components: {
`

**Comment by Beihao-Zhou** [comment]
@natalyapeixoto Could you please take a look at the issue again? I used the same method as @daydy16 but the problem is still there.
